name: Установка Python и Poetry
description: Установка Python, Poetry и зависимостей проекта с кэшированием

inputs:
  python-version:
    description: Версия Python
    required: false
    default: '3.13'

runs:
  using: composite
  steps:
    - name: Установка Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Кэширование pip и Poetry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-pip-${{ hashFiles('**/pyproject.toml','**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-pip-

    - name: Установка Poetry и зависимостей проекта
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry
        export POETRY_VIRTUALENVS_IN_PROJECT=true
        poetry install --no-interaction --no-ansi
