"""add order to variant_task

Revision ID: 61b89baaad9c
Revises: b93aaecf9d95
Create Date: 2025-12-14 15:21:08.649669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b89baaad9c'
down_revision = 'b93aaecf9d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variant_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_type', sa.String(length=50), nullable=True, comment='single, double, или table'))
        batch_op.add_column(sa.Column('answer_count', sa.Integer(), nullable=True, comment='Число колонок в таблице'))
        batch_op.create_index('ix_variant_tasks_order', ['variant_id', 'order'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variant_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_variant_tasks_order')
        batch_op.drop_column('answer_count')
        batch_op.drop_column('answer_type')

    # ### end Alembic commands ###
