"""add author_id to variants, registered_at to users

Revision ID: 681ebbf0351e
Revises: bf6b4e652997
Create Date: 2025-12-10 13:12:43.030085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681ebbf0351e'
down_revision = 'bf6b4e652997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_variants_author_id'), ['author_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_variants_author_id_users'), 'users', ['author_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_variants_author_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_variants_author_id'))
        batch_op.drop_column('author_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('registered_at')

    # ### end Alembic commands ###
