"""Add CASCADE delete for attempts when variant is deleted

Revision ID: ca3a4204e3e5
Revises: dd2faa060877
Create Date: 2025-12-25 01:03:32.609082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3a4204e3e5'
down_revision = 'dd2faa060877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_attempts_variant_id_variants'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_attempts_variant_id_variants'), 'variants', ['variant_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_attempts_variant_id_variants'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_attempts_variant_id_variants'), 'variants', ['variant_id'], ['id'])

    # ### end Alembic commands ###
