"""add author_id to tasks

Revision ID: e27494632bcf
Revises: e4947f9035b4
Create Date: 2025-12-06 18:55:43.937201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e27494632bcf'
down_revision = 'e4947f9035b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_author_id'), ['author_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_tasks_author_id_users'), 'users', ['author_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_author_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tasks_author_id'))
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
