"""removed unique constraint from attempts

Revision ID: fb2059f320ea
Revises: 61b89baaad9c
Create Date: 2025-12-14 15:54:21.529658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb2059f320ea'
down_revision = '61b89baaad9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_variant_attempt'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_variant_attempt'), ['user_id', 'variant_id'])

    # ### end Alembic commands ###
